# -*- coding: utf-8 -*-
"""BigTechs_Performance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hVW9jFfc_7-kldCw4S6-9eP3oxSe-k05
"""

# Install ffn library
!pip install -q ffn

# Commented out IPython magic to ensure Python compatibility.
# Importing libraries
import ffn
import matplotlib.pyplot as plt
# Plotting on Jupyter Notebook
# %matplotlib inline 
# Control the default size of figures in this Jupyter notebook
# %pylab inline 
# Change the size of plots
pylab.rcParams['figure.figsize'] = (15, 9)

# Import prices (adj. close) and define data frame variable
prices = ffn.get('amzn,aapl,googl,fb', start='2015-01-01')

# Data frame glimpse
prices.head()

# Relative performance graphically using rebase for a common starting point
ax = prices.rebase().plot()

# Returns of each security and plot histogram 
returns = prices.to_returns().dropna()
ax = returns.hist(figsize(15, 8))

# Finding correlation with a heat map
returns.plot_corr_heatmap()

# Performance metrics
perf = prices.calc_stats()
perf.display();